added modals for sell & outOfService
PhilipW97/SurfSegelcenter pull request #90
Opened 2021-06-17 09:49 UTC by pascalne2505

not sure if it is the best way to do it how i did it in the JS part. If there is something I could improve, please tell me @xyse @PhilipW97

2021-06-18 13:56 UTC, PhilipW97 requested changes

2021-06-18 13:56 UTC, PhilipW97 commented on src/main/resources/templates/sportsequipment-details.html
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
You do not need this. It is a big package and you only use it twice. In booth cases you can just use vanilla js

2021-06-18 13:56 UTC, PhilipW97 commented on src/main/resources/templates/sportsequipment-details.html
> +	$('.modalElement').addClass('hide')
This is the first time jquery is being used. This is just a selector and can easily be replaced by vanilla js selectors: `document.getElementsByClassName("modalElement")`. Here you have to be aware that `document.getElementsByClassName("modalElement")` is returning an array of all elements with that class, because a class can appear multiple times on the same page.
 It would be better to add an id to the `.modalElement` in order to be able to select it properly by `getElementById('modalElement')`. Because ids can/should only appear once at a page this is returning your desired element instead of  an array.

The `addClass` function is also jquery syntax. Here you can also just use vanilla js as you used in line [305](https://github.com/PhilipW97/SurfSegelcenter/pull/90/files). and replace the `remove` with an `add` --> `classList.add('hide')`

`document.getElementById("modalElement").classList.add('hide')`

2021-06-18 13:56 UTC, PhilipW97 commented on src/main/resources/templates/sportsequipment-details.html
> +		$('.modalElement').addClass('hide')
Same as [here](https://github.com/PhilipW97/SurfSegelcenter/pull/90/files#diff-7aed7dd2b49c887d1f211fbf054d4ccda179dca88865b76c95ff2cbed7835d96R312)

2021-06-18 19:49 UTC, pascalne2505 commented on src/main/resources/templates/sportsequipment-details.html
> +	$('.modalElement').addClass('hide')
I removed jquery from the script and replaced it with vanilla js.

I am still doing it with `document.getElementsByClassName("modalElement")` because like this i dont need to pick every element itself to add the "hide" class. If you think it would be better with the IDs, I can change it, just let me know

2021-06-19 14:30 UTC, PhilipW97 approved these changes

2021-06-19 14:49 UTC, merged